version: '3'

services:
  banco-armazem:
    image: postgres:12.6
    container_name: banco-armazem
    restart: unless-stopped
    environment:
      POSTGRES_DB: armazem-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "1515:5432"
